config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'users/new'
  resources :sessions
  resource :users do
  resources :albums
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in
  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums.all
  end

  # GET /albums/1
  # GET /albums/1.json

  # GET /albums/new
  def new
    @album = current_user.albums.new
  end

  def show
  end

  # GET /albums/1/edit
  def edit
    # @album = current_user.albums.find(params[:id])
    respond_to do |format|
      if @album.update
        format.html { render :show, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to users_album_path(@album), notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def edit
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :image, :artist, :url)
    end

    def set_album
      @album = current_user.albums.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_logged_in
  return true if current_user
  return redirect_to root_path

  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.
    find_by(username: params[:username]).
    try(:authenticate, params[:password])

    # return render action: 'new' unless @user
    if @user
      flash[:success] = "Welcome back #{@user.username}."
      session[:user_id] = @user.id
      redirect_to users_albums_path
    else
      flash[:error] = "Something went wrong. Please try again."
      redirect_to root_path
    end

  end

  def index
    session[:user_id] = @user.id
    redirect_to albums_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    return render action: 'new' unless @user.save
    redirect_to root_path, notice: 'Created user'
  end

  private
  def user_params
    params.
    require(:user).
    permit(:username,
    :password,
    :password_confirmation)
end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, url: '/users/albums', local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :'Link to full album' %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <%= form.hidden_field :user, id: album.user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', users_album_path %> |
<%= link_to 'Back', users_albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Collection</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Listen on Youtube</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.image  %></td>
        <td><%= album.url %></td>
        <td><%= link_to 'Show', users_album_path(album) %></td>
        <td><%#= link_to 'Edit', edit_method-url, remote: true %></td>
        <td><%#= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_users_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', users_albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
<%= image_tag @album.image.url %>
</p>

<p>
  <strong>Listen on Youtube:</strong>
  <%= @album.url %>
</p>

<%#= link_to 'Edit', edit_users_album_path(@album) %>
<%= link_to 'Back', users_albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VinylParty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
<p>
<%= f.label :username %>
<%= f.text_field :username %>
</p>
<p>
<%= f.label :password %>
<%= f.password_field :password %>
</p>
<p>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>